extend type AIInteraction {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "AIInteraction", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `AIInteraction`.`service`. It must match the value of `Service`.`id`. See `@ref` for how to customize it.
  """
  serviceId: UUID! @fdc_generated(from: "AIInteraction.service", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `AIInteraction`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "AIInteraction.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Request {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Request", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Request`.`service`. It must match the value of `Service`.`id`. See `@ref` for how to customize it.
  """
  serviceId: UUID! @fdc_generated(from: "Request.service", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Request`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Request.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Service {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Service", purpose: IMPLICIT_KEY_FIELD)
}
extend type SubscriptionType {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "SubscriptionType", purpose: IMPLICIT_KEY_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
extend type UserSubscription {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "UserSubscription", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `UserSubscription`.`subscriptionType`. It must match the value of `SubscriptionType`.`id`. See `@ref` for how to customize it.
  """
  subscriptionTypeId: UUID! @fdc_generated(from: "UserSubscription.subscriptionType", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `UserSubscription`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "UserSubscription.user", purpose: IMPLICIT_REF_FIELD)
}
