# Base image for development environment
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies to leverage Docker cache
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .