name: Gemini Auto Review

on:
  push:
    branches: [ main ]

jobs:
  review-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run Gemini Review
        run: |
          npm install
          node scripts/geminiReview.js
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
